### PR TITLE
Better styling for the superprompt bar

### PR DESCRIPTION
**Pull request by fardeem**
Something that was bothering me is that the windows were rounded but the prompt bar was not so I changed that. Also
- prompt bar changes color when in focus. @swyxio feel free to change the color
- The margin between the left hand side and the right hand side of the prompt bar is now equal (box sizing border box lol)

If you want I can implement the design from #24 entirely

image

### CODE REVIEW

**Comment by swyxio** [comment]
classic, border box solves everything

**Comment by swyxio** [comment]
looking great! just noticed there was also movement on #24, thanks for pointing that out!

**Comment by fardeem** [comment]
Let's merge this first and I'll implement the design soon and get that PR up.

**Comment by seanoliver** [comment]
Oh man I've been wanting to do something about the input box spacing. Looks great. Thanks, @fardeem.

**Pull request merged**
