### PR TITLE
first rewrite of menubar into full chat browser

### LINKED ISSUE #78: Bug: Bing URLs and paste not working
## Behavior
* Paste into bing chat does nothing
* Clicking on links does nothing:
image

* cmd+click gives:

image

## Steps to reproduce
* menubar 0.0.11-x64, installed from dmg
* Ventura 13.4.1
* Logged into Bing, tried to paste and click on links in response

Will consider installing from src to use devtools

### LINKED ISSUE #90: Setup issues
The first of the 4 frames works fine, but:
- 2nd: when I click X, Start chatting, and learn more, nothing happens
- 3rd: login code doesn't work (tried a few times, made sure not to copy/paste a space in the number)
- 4th: blank

image

### LINKED ISSUE #105: [Request] Enable Automatic Updates + launch on Startup
Would be nice not to have to download the latest binary after each release and have a setting where the app can update itself and/or alert you to the latest version so you can do the update.

https://www.electronjs.org/docs/latest/api/auto-updater

### LINKED ISSUE #108: Bug: window no longer opens when we click the menubar icon
this regression happened sometime between v0.16 and the current main branch. 

lets make sure to fix this or investigate @seanoliver 

i think regression happeend in #99

### PR DESCRIPTION
**Pull request by swyxio**
now the menubar functionality is secondary, first and foremost this is a persistent browser that sticks around as you run your chats

image

incidental things also fixed:
- auto updates - closes #105 
- sso login popup issues - closes #90 (cc @lorensr)
- bing links should work - closes #78 
- click icon to open works again - closes #108

### CODE REVIEW

**Comment by seanoliver** [comment]
I really love this. A few items we should consider addressing as a follow up:

1. It's hard to click on the top to move the window around. Also there's no minimize maximize close buttons which is more of a standard for a full app
2. On Mac, the menubar still looks like it's focused on the last app you were using rather than the current app.
CleanShot 2023-08-09 at 09 29 33
3. Submit still not working on Smol Talk but that should be easy for us to handle

**Comment by seanoliver** [comment]
@swyxio looks great to me! i just swapped out smol talk for bing as default providers since talk has a submission bug at the moment.

**Comment by swyxio** [comment]
i moved out the "browser pane" to a little options menu that also supports drag and drop, as well as arbitrary add

image

all windows are still singletons for now.

**Comment by swyxio** [comment]
the last version before the rewrite is preserved here https://github.com/smol-ai/menubar/tree/lastSmolMenubarVersion

**Pull request merged**
