### PR TITLE
testing gh action

### PR DESCRIPTION
**Pull request by seanoliver**

### CODE REVIEW

**Comment by swyxio** [comment]
can also try it out on another repo so you can move faster

**Comment by swyxio** [comment]
does chatgpt know how to write these things yet?

**Comment by seanoliver** [comment]
No worries I think I've got it — I just didn't resolve because I passed out at my desk last night 😆 😭

**Comment by seanoliver** [comment]
Also ChatGPT's not great but Phind FTW!

**Comment by swyxio** [comment]
ooo go phind

also nooo get enough sleep!

**Review by swyxio — APPROVED** [review]
lgtm, merge whenever you like. i do sometimes commit directly to main instead of making a pull request like a good boy, i'd normally want to check that it ALSO does the prettier thing on a commit (as opposed to a pull request), but i'm not sure if the changes that would require are worth it. just thought i'd mention but not a blocker

**Comment by seanoliver** [comment]
Boom! Alright Now it will work on any push to main or PR!

GH actions are super cool. Are people still using Jenkins or do I sound like a boomer asking that question? lol

**Comment by swyxio** [comment]
@seanoliver yeah github actions have replaced jenkins

this one is worth a quick blogpost fyi

**Pull request merged**
